{{- if .Values.configs.clientserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configs.clientserver.name }}
  namespace: {{ .Values.configs.clientserver.namespace }}
  labels:
    app: {{ .Values.configs.clientserver.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.configs.clientserver.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configs.clientserver.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.configs.clientserver.name }}
      containers:
      - name: tas-clients
        image: "{{ template "image" .Values.configs.clientserver.image }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.configs.clientserver.port }}
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- end}}
