{{- if .Values.configs.clientserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.configs.clientserver.name }}
  name: {{ .Values.configs.clientserver.name }}
  namespace: {{ .Values.configs.clientserver.namespace }}
spec:
  ports:
  - name: {{ .Values.configs.clientserver.port }}-tcp
    port: {{ .Values.configs.clientserver.port }}
    protocol: TCP
    targetPort: {{ .Values.configs.clientserver.port }}
  selector:
    app: {{ .Values.configs.clientserver.name }}
  type: ClusterIP
{{- end }}
