{{- if .Values.configs.rekorui.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.configs.rekorui.name }}
  name: {{ .Values.configs.rekorui.name }}
  namespace: {{ .Values.configs.rekorui.namespace }}
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.configs.rekorui.name }}
  type: ClusterIP
{{- end }}
