apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.configs.segment_backup_job.name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - get
  - list 