{{ if .Values.configs.pull_secret.secret_create }}
{{- if and (not .Values.configs.pull_secret.default_pull_secret_value) (not .Values.configs.pull_secret.value) }}
{{- fail "A Valid Pull Secret Must be Provided when `secret_create` is set to `true`" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configs.pull_secret.name }}
  namespace: {{ .Values.configs.pull_secret.namespace }}
type: Opaque
data:
  pull-secret.json: {{ include "trusted-artifact-signer.pullSecret" . }}
{{- end }}
