global:
  # -- DNS name to generate environment variables and consoleCLIDownload urls.
  # By default, in OpenShift, the value for this is
  # apps.$(oc get dns cluster -o jsonpath='{ .spec.baseDomain }')
  appsSubdomain: ""

configs:
  segment_backup_job:
    enabled: false
    namespace_create: false
    image:
      registry: quay.io
      repository: redhat-user-workloads/rhtas-tenant/access-1-0-gamma/segment-backup-job-1-0-gamma
      version: "sha256:24019bfe598d79774135398e8b186e56969e7f6e3dfdeb4a965ca40bd21cb6fb"
      pullPolicy: IfNotPresent
    rolebindings:
      - segment-backup-job
    name: segment-backup-job
    namespace: trusted-artifact-signer-monitoring
  clientserver:
    # -- Whether to create the OpenShift resource 'ConsoleCLIDownload' for each binary.
    # -- This can only be enabled if the OpenShift CRD is registered.
    consoleDownload: true
    # -- Whether to create the OpenShift route resource
    route: true
    name: tas-clients
    namespace_create: true
    namespace: trusted-artifact-signer-clientserver
    image:
      registry: registry.redhat.io
      repository: rhtas-tech-preview/client-server-rhel9
      version: "sha256:eebda321cdc0cb5bd0ce2df83a661e566f5a48a34bd9d192e72d4300347956e3"
      pullPolicy: IfNotPresent

  rekorui:
    enabled: true
    route: true
    name: rekor-ui
    namespace_create: true
    namespace: rekor-ui
    image:
      registry: registry.redhat.io
      repository: rhtas-tech-preview/rekor-search-ui-rhel9
      version: "sha256:325f1e84936c31e02bddb2bc4fff07c3a55c2e556deba72e99f4ec99aa589cca"
      imagePullPolicy: Always
    subdomain: rekorui.appsSubdomain
  ctlog:
    namespace: ctlog-system
    namespace_create: true
    # -- Names for rolebindings to add clusterroles to ctlog serviceaccounts.
    # The names must match the serviceaccount names in the ctlog namespace.
    rolebindings:
      - ctlog
      - ctlog-createtree
      - trusted-artifact-signer-ctlog-createctconfig

  rekor:
    namespace_create: true
    namespace: rekor-system
    # -- names for rolebindings to add clusterroles to rekor serviceaccounts.
    # The names must match the serviceaccount names in the rekor namespace.
    rolebindings:
      - rekor-redis
      - rekor-server
      - trusted-artifact-signer-rekor-createtree
    # -- Signer holds secret that contains the private key used to sign entries and the tree head of the transparency log
    # When this section is left out, scaffold.rekor creates the secret and key.
    signer:
      secret:
        # -- Name of the secret to create with the private key data. This name must match the value in
        # scaffold.rekor.server.signer.signerFileSecretOptions.secretName.
        name: ""
        # -- Private encrypted signing key
        private_key: ""
        # -- File containing a private encrypted signing key
        private_key_file: ""
    #  -- With ClusterMonitoring enabled, a ServiceMonitor and RBAC is created. This adds a  metrics target from rekor-server
    #  in the openshift-monitoring namespace scraped by prometheus along with other cluster-monitoring targets.
    clusterMonitoring:
      enabled: true
      endpoints:
        - interval: 30s
          port: 2112-tcp
          scheme: http
    backfillRedis:
      enabled: true
      schedule: "0 0 * * *"
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/backfill-redis-rhel9
        version: "sha256:028b3090bd0677351cc40de4a49246a5cdd57bdd2ad1668e4d7df0a7c01f20c7"
        pullPolicy: IfNotPresent


  fulcio:
    namespace_create: true
    namespace: fulcio-system
    # -- Names for rolebindings to add clusterroles to fulcio serviceaccounts.
    # The names must match the serviceaccount names in the fulcio namespace.
    rolebindings:
      - fulcio-createcerts
      - fulcio-server
    server:
      #  -- Secret to create with fulcio signing backend certificate and keys.
      #  Leave this section out if a secret already exists in the fulcio namespace.
      #  The secret.name must match the value of scaffold.fulcio.server.secret and
      #  also tuf.secrets.fulcio.name. For details on certificate and key requirements,
      #  see https://github.com/sigstore/fulcio/blob/main/docs/setup.md#ca-certificate-requirements
      secret:
        name: ""
        # -- password to decrypt the signing key
        password: ""
        # -- signer public key
        public_key: ""
        # -- a PEM-encoded encrypted signing key
        private_key: ""
        # -- file containing signer public key
        public_key_file: ""
        # -- file containing a PEM-encoded encrypted signing key
        private_key_file: ""
        # -- fulcio root certificate authority (CA)
        root_cert: ""
        # -- file containing fulcio root certificate authority (CA)
        root_cert_file: ""
    #  -- With ClusterMonitoring enabled, a ServiceMonitor and RBAC is created. This adds a  metrics target from fulcio-server
    #  in the openshift-monitoring namespace scraped by prometheus along with other cluster-monitoring targets.
    clusterMonitoring:
      enabled: true
      endpoints:
        - interval: 30s
          port: 2112-tcp
          scheme: http

  trillian:
    namespace_create: true
    namespace: trillian-system
    # -- names for rolebindings to add clusterroles to trillian serviceaccounts.
    # The names must match the serviceaccount names in the trillian namespace.
    rolebindings:
      - trillian-logserver
      - trillian-logsigner
      - trillian-mysql

  tuf:
    namespace: tuf-system
    namespace_create: true
    # -- names for rolebindings to add clusterroles to tuf serviceaccounts.
    # The names must match the serviceaccount names in the tuf namespace.
    rolebindings:
      - tuf
      - tuf-secret-copy-job

  cosign_deploy:
    enabled: false
    namespace: cosign
    namespace_create: true
    # -- names for rolebindings to add clusterroles to cosign serviceaccounts.
    # The names must match the serviceaccount names in the cosign namespace.
    rolebindings:
      - cosign
    # -- Name of deployment
    name: cosign
    # -- Image containing the cosign binary as well as environment variables with the base domain injected.
    image:
      registry: quay.io
      repository: redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2
      version: sha256:83e03294d6dfe8443762a735b2abb1171043cbfb93694a459e4432e520acf9a2
      pullPolicy: IfNotPresent

rbac:
  # -- clusterrole to be added to sigstore component serviceaccounts.
  clusterrole: system:openshift:scc:anyuid

# github.com/sigstore/helm-charts/charts
scaffold:
  ctlog:
    enabled: true
    forceNamespace: ctlog-system
    fullnameOverride: ctlog
    namespace:
      create: false
      name: ctlog-system
    server:
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/ct-server-rhel9
        version: "sha256:c99e09403fef657f9e03d29991e042d9b26d4a3ebd5a74c50bb7b2b6555693ca"
        pullPolicy: IfNotPresent
    createctconfig:
      backoffLimit: 30
      enabled: true
      initContainerImage:
        curl:
          registry: registry.access.redhat.com
          repository: ubi9/ubi-minimal
          version: latest
          imagePullPolicy: IfNotPresent
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/createctconfig-rhel9
        version: "sha256:7c38f48b0bd7451941d33502fbdd9500c9550cb3e97409eecf21d0a06a5c0f44"
        pullPolicy: IfNotPresent
    createcerts:
      fullnameOverride: ctlog-createcerts
    createtree:
      fullnameOverride: ctlog-createtree
      displayName: ctlog-tree
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/createtree-rhel9
        version: "sha256:ec13e102555022c210361da239ec3cfe2e0d7b7fc3fea51d40e75fcbc9658a42"
        pullPolicy: IfNotPresent
  fulcio:
    enabled: true
    forceNamespace: fulcio-system
    ctlog:
      enabled: false
      createctconfig:
        logPrefix: sigstorescaffolding
    namespace:
      name: fulcio-system
      create: false
    createcerts:
      enabled: false
      fullnameOverride: fulcio-createcerts
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/createcerts-rhel9
        version: "sha256:084568637d473ca5590cfded4d3687136803afb2d72b1fe55801b2f6109f3bf6"
        pullPolicy: IfNotPresent
    server:
      fullnameOverride: fulcio-server
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/fulcio-rhel9
        version: "sha256:dc1f10ddc34cce14a6e35f1448b6d1af1804dfbdb2cfe340ec5d133689a8fa92"
        pullPolicy: IfNotPresent
      # If content and/or files not provided in configs.fulcio.secret
      # then this secret must exist in fulcio-system ns. See ../quickstart-with-keycloak.md
      # for how to create this secret.
      secret: fulcio-secret-rh
      ingress:
        http:
          enabled: true
          className: ""
          annotations:
            route.openshift.io/termination: "edge"
          hosts:
          - host: fulcio.appsSubdomain
            path: /

  rekor:
    initContainerImage:
      curl:
        registry: registry.access.redhat.com
        repository: ubi9/ubi-minimal
        version: sha256:06d06f15f7b641a78f2512c8817cbecaa1bf549488e273f5ac27ff1654ed33f0
        imagePullPolicy: IfNotPresent
    enabled: true
    forceNamespace: rekor-system
    fullnameOverride: rekor
    namespace:
      name: rekor-system
      create: false
    trillian:
      enabled: false
    redis:
      fullnameOverride: rekor-redis
      args:
        - /usr/bin/run-redis
        - --bind
        - 0.0.0.0
        - --appendonly
        - "yes"
      image:
        registry: quay.io
        repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/redis-0-6
        version: sha256:acf920baf6ee1715c0c9d7ddf69867d331c589d3afa680048c508943078d9585
        pullPolicy: IfNotPresent
    server:
      fullnameOverride: rekor-server
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/rekor-server-rhel9
        version: "sha256:45a5dfcedb1aaa7c15f4f444a9d0440ea3413e8a245a77a5aa562205a91627a3"
        pullPolicy: IfNotPresent
      # when providing contents of secret with configs.rekor.signer
      # the signer sections must also be provided here
      signer: /key/private
      signerFileSecretOptions:
        secretName: rekor-private-key
        secretMountPath: /key
        secretMountSubPath: private
        privateKeySecretKey: private
      ingress:
        className: ""
        annotations:
          route.openshift.io/termination: "edge"
        hosts:
          - host: rekor.appsSubdomain
            path: /

    createtree:
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/createtree-rhel9
        version: "sha256:ec13e102555022c210361da239ec3cfe2e0d7b7fc3fea51d40e75fcbc9658a42"
        pullPolicy: IfNotPresent
  trillian:
    enabled: true
    forceNamespace: trillian-system
    fullnameOverride: trillian
    namespace:
      create: false
      name: trillian-system
    createdb:
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/createdb-rhel9
        version: "sha256:96673a1f651c141e9c7cd4fe278f04978d33d32c3d10fee829612b00fd5e2d4b"
        pullPolicy: IfNotPresent
    initContainerImage:
      netcat:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/trillian-netcat-rhel9
        version: "sha256:c4c5a553ea96b2bf98434d9fb21d0a1bf5649b85daa02698748cef89b88c2471"
      curl:
        registry: registry.access.redhat.com
        repository: ubi9/ubi-minimal
        version: latest
        imagePullPolicy: IfNotPresent
    redis:
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/redis-trillian-rhel9
        version: sha256:914089e0e8407420ce07f44dad49da75d34c88eac6314ea8d6e45ff0745e4b42
        pullPolicy: IfNotPresent
      args: []

    logSigner:
      name: trillian-logsigner
      fullnameOverride: trillian-logsigner
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/trillian-logsigner-rhel9
        version: "sha256:015f430f8f966d5cf83cdaad5ba5ca87dd75a83e64abd229c00ddd370f3c393b"
        pullPolicy: IfNotPresent
    logServer:
      name: trillian-logserver
      fullnameOverride: trillian-logserver
      portHTTP: 8090
      portRPC: 8091
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/trillian-logserver-rhel9
        version: "sha256:d6bebd674b5d66bb742bf96dbbea761e2fa73a9fabd9be8a48cefbfc906e990c"
        pullPolicy: IfNotPresent
    mysql:
      fullnameOverride: trillian-mysql
      gcp:
        scaffoldSQLProxy:
          registry: registry.redhat.io
          repository: rhtas-tech-preview/cloudsqlproxy-rhel9
          version: sha256:f6879364d41b2adbe339c6de1dae5d17be575ea274786895448ee4277831cb7f
      image:
        registry: registry.redhat.io
        repository: rhtas-tech-preview/trillian-database-rhel9
        version: "sha256:3e7210bd4943c266eabaee33a50d86241c66ed69463f208bcc0b0b7373c22af0"
        pullPolicy: IfNotPresent
      args: []
      securityContext:
        fsGroup: 0
      livenessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
      readinessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
  tuf:
    namespace:
      create: false
      name: tuf-system
    forceNamespace: tuf-system
    fullnameOverride: tuf
    secrets:
      fulcio:
        name: fulcio-secret-rh
        path: fulcio_v1.crt.pem
      rekor:
        name: rekor-public-key
        path: rekor.pub
      ctlog:
        name: ctlog-public-key
        path: ctfe.pub

    enabled: true
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      http:
        hosts:
          - host: tuf.appsSubdomain
            path: /
    deployment:
      registry: registry.redhat.io
      repository: rhtas-tech-preview/tuf-server-rhel9
      version: "sha256:0702c1d59306e743a8fcf01785c25c5d5edb64199c8e626b4438ffb08b88a5e5"


  copySecretJob:
    name: copy-secrets-job
    enabled: true
    registry: registry.redhat.io
    repository: openshift4/ose-cli
    version: latest
    imagePullPolicy: IfNotPresent
    serviceaccount: tuf-secret-copy-job
    backoffLimit: 1000

  tsa:
    enabled: false
    forceNamespace: tsa-system
    namespace:
      create: false
      name: tsa-system
    server:
      fullnameOverride: tsa-server
